use crate::definitions::{Definitions, LauncherType, Platform};
use std::fmt::Write;
use std::path::Path;

pub fn generate(defs: &Definitions, dotfiles_dir: &Path) -> String {
    let mut out = String::new();
    let dotfiles = dotfiles_dir.to_string_lossy().replace('\\', "/");

    writeln!(out, "# Auto-generated by dotcli — DO NOT EDIT").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "{}", APPLY_HELPER).unwrap();

    if !defs.alias.is_empty() {
        writeln!(out, "# --- Aliases ---").unwrap();
        for a in &defs.alias {
            let args_str = if a.args.is_empty() {
                String::new()
            } else {
                let parts: Vec<String> = a.args.iter().map(|x| bash_squote(x)).collect();
                format!(" {}", parts.join(" "))
            };
            writeln!(
                out,
                "{name}() {{ {cmd}{args} \"$@\"; }}",
                name = a.name,
                cmd = a.command,
                args = args_str,
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    if !defs.script.is_empty() {
        writeln!(out, "# --- Script wrappers ---").unwrap();
        for s in &defs.script {
            let path = format!("{}/{}", dotfiles, s.path.replace('\\', "/"));
            writeln!(
                out,
                "{name}() {{ pwsh -NoProfile -File {path} \"$@\"; }}",
                name = s.name,
                path = bash_squote(&path),
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    let win_launchers: Vec<_> = defs
        .launcher
        .iter()
        .filter(|l| l.platform.as_ref() != Some(&Platform::Macos))
        .collect();
    if !win_launchers.is_empty() {
        writeln!(out, "# --- Launchers ---").unwrap();
        for l in &win_launchers {
            match l.launcher_type {
                LauncherType::Uri => {
                    let uri = l.uri.as_ref().unwrap();
                    writeln!(
                        out,
                        "{name}() {{ explorer.exe {uri}; }}",
                        name = l.name,
                        uri = bash_squote(uri),
                    )
                    .unwrap();
                }
                LauncherType::StartApp => {
                    let app = l.app_name.as_ref().unwrap();
                    let ps_cmd = format!(
                        "explorer \"shell:AppsFolder\\$((Get-StartApps '{}' | Select-Object -First 1).AppID)\"",
                        ps_squote_inner(app)
                    );
                    writeln!(
                        out,
                        "{name}() {{ pwsh -NoProfile -Command {cmd}; }}",
                        name = l.name,
                        cmd = bash_squote(&ps_cmd),
                    )
                    .unwrap();
                }
                LauncherType::Exe => {
                    let raw_path = l.path.as_ref().unwrap();
                    let path_part = if raw_path.contains("{PROGRAM_FILES}") {
                        // PS double-quoted to expand $env:ProgramFiles
                        let p = raw_path.replace("{PROGRAM_FILES}", "$env:ProgramFiles");
                        format!("\"{}\"", p.replace('"', "`\""))
                    } else {
                        format!("'{}'", ps_squote_inner(raw_path))
                    };
                    let arglist = if l.args.is_empty() {
                        String::new()
                    } else {
                        let pwsh_args: Vec<String> = l
                            .args
                            .iter()
                            .map(|a| format!("'{}'", ps_squote_inner(a)))
                            .collect();
                        format!(" -ArgumentList {}", pwsh_args.join(","))
                    };
                    let ps_cmd = format!("Start-Process -FilePath {}{}", path_part, arglist);
                    writeln!(
                        out,
                        "{name}() {{ pwsh -NoProfile -Command {cmd}; }}",
                        name = l.name,
                        cmd = bash_squote(&ps_cmd),
                    )
                    .unwrap();
                }
            }
        }
        writeln!(out).unwrap();
    }

    let cmds: Vec<_> = defs.command.iter().filter(|c| c.enabled).collect();
    if !cmds.is_empty() {
        writeln!(out, "# --- Commands (via dotcli) ---").unwrap();
        for c in &cmds {
            if c.modifies_shell {
                writeln!(
                    out,
                    "{name}() {{ local _o; _o=$(dotcli {sub} \"$@\"); _dotcli_apply <<<\"$_o\"; }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "{name}() {{ dotcli {sub} \"$@\"; }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            }
        }
    }

    out
}

fn bash_squote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn ps_squote_inner(s: &str) -> String {
    s.replace('\'', "''")
}

const APPLY_HELPER: &str = r#"_dotcli_apply() {
    local json
    json=$(cat)
    [ -z "$json" ] && return 0
    if ! command -v jq >/dev/null 2>&1; then
        printf 'dotcli: jq is required for shell-modifying commands\n' >&2
        return 1
    fi
    local key val cd_path lvl txt prog
    while IFS= read -r key; do [ -n "$key" ] && unset "$key"; done < <(printf '%s' "$json" | jq -r '.unset_env[]? // empty')
    while IFS=$'\t' read -r key val; do [ -n "$key" ] && export "$key=$val"; done < <(printf '%s' "$json" | jq -r '.set_env // {} | to_entries[] | "\(.key)\t\(.value)"')
    cd_path=$(printf '%s' "$json" | jq -r '.cd // empty')
    [ -n "$cd_path" ] && cd "$cd_path"
    while IFS=$'\t' read -r lvl txt; do
        case "$lvl" in
            warn) printf '\033[33m%s\033[0m\n' "$txt" ;;
            error) printf '\033[31m%s\033[0m\n' "$txt" ;;
            *) printf '\033[32m%s\033[0m\n' "$txt" ;;
        esac
    done < <(printf '%s' "$json" | jq -r '.messages[]? | "\(.level)\t\(.text)"')
    prog=$(printf '%s' "$json" | jq -r '.exec.program // empty')
    if [ -n "$prog" ]; then
        if [ "$prog" = "claude" ]; then
            printf '\033]1337;SetUserVar=app=Y2xhdWRl\007'
        fi
        local exec_args=()
        local arg
        while IFS= read -r arg; do exec_args+=("$arg"); done < <(printf '%s' "$json" | jq -r '.exec.args[]? // empty')
        exec "$prog" "${exec_args[@]}"
    fi
}
"#;
