use crate::definitions::{Definitions, LauncherType, Platform};
use std::fmt::Write;

pub fn generate(defs: &Definitions) -> String {
    let mut out = String::new();

    writeln!(out, "# Auto-generated by dotcli — DO NOT EDIT").unwrap();
    writeln!(out).unwrap();

    // _dotcli_apply helper
    writeln!(out, "{}", APPLY_HELPER).unwrap();

    // Aliases
    if !defs.alias.is_empty() {
        writeln!(out, "# --- Aliases ---").unwrap();
        for a in &defs.alias {
            if a.args.is_empty() {
                writeln!(out, "alias {name} = {cmd}", name = a.name, cmd = a.command,).unwrap();
            } else {
                // nushell alias can include args
                writeln!(
                    out,
                    "alias {name} = {cmd} {args}",
                    name = a.name,
                    cmd = a.command,
                    args = a.args.join(" "),
                )
                .unwrap();
            }
        }
        writeln!(out).unwrap();
    }

    // Launchers (Windows — nushell `start` opens URIs and exes)
    let win_launchers: Vec<_> = defs
        .launcher
        .iter()
        .filter(|l| l.platform.as_ref() != Some(&Platform::Macos))
        .collect();
    if !win_launchers.is_empty() {
        writeln!(out, "# --- Launchers ---").unwrap();
        for l in &win_launchers {
            match l.launcher_type {
                LauncherType::Uri => {
                    writeln!(
                        out,
                        "def {name} [] {{ start {uri} }}",
                        name = l.name,
                        uri = l.uri.as_ref().unwrap(),
                    )
                    .unwrap();
                }
                LauncherType::Exe => {
                    let path = l
                        .path
                        .as_ref()
                        .unwrap()
                        .replace("{PROGRAM_FILES}", "$env.ProgramFiles");
                    if l.args.is_empty() {
                        writeln!(
                            out,
                            "def {name} [] {{ start $\"({path})\" }}",
                            name = l.name,
                        )
                        .unwrap();
                    } else {
                        let args_str = l.args.iter().map(|a| format!("\"{a}\"")).collect::<Vec<_>>().join(" ");
                        writeln!(
                            out,
                            "def {name} [] {{ ^$\"({path})\" {args} }}",
                            name = l.name,
                            args = args_str,
                        )
                        .unwrap();
                    }
                }
                LauncherType::StartApp => {
                    // start_app is PowerShell-specific, skip for nushell
                }
            }
        }
        writeln!(out).unwrap();
    }

    // Complex commands (dotcli subcommands)
    let cmds: Vec<_> = defs.command.iter().filter(|c| c.enabled).collect();
    if !cmds.is_empty() {
        writeln!(out, "# --- Commands (via dotcli) ---").unwrap();
        for c in &cmds {
            if c.modifies_shell {
                writeln!(
                    out,
                    "def {name} [...args: string] {{ dotcli {sub} ...$args | _dotcli_apply }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "def {name} [...args: string] {{ dotcli {sub} ...$args }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            }
        }
    }

    out
}

const APPLY_HELPER: &str = r#"def _dotcli_apply [] {
    let action = ($in | from json)
    if ($action | get -o set_env | is-not-empty) {
        $action.set_env | transpose k v | each { |r| load-env {($r.k): $r.v} } | ignore
    }
    if ($action | get -o unset_env | is-not-empty) {
        $action.unset_env | each { |k| hide-env $k } | ignore
    }
    if ($action | get -o cd | is-not-empty) { cd $action.cd }
    if ($action | get -o messages | is-not-empty) {
        $action.messages | each { |m| print $m.text } | ignore
    }
    if ($action | get -o exec | is-not-empty) {
        ^($action.exec.program) ...($action.exec.args)
    }
}
"#;
