use crate::definitions::{Definitions, LauncherType, Platform};
use std::fmt::Write;
use std::path::Path;

pub fn generate(defs: &Definitions, dotfiles_dir: &Path) -> String {
    let mut out = String::new();
    let dotfiles = dotfiles_dir.to_string_lossy().replace('\\', "/");

    writeln!(out, "# Auto-generated by dotcli — DO NOT EDIT").unwrap();
    writeln!(out).unwrap();

    // _dotcli_apply helper
    writeln!(out, "{}", APPLY_HELPER).unwrap();

    // Aliases
    if !defs.alias.is_empty() {
        writeln!(out, "# --- Aliases ---").unwrap();
        for a in &defs.alias {
            if a.args.is_empty() {
                writeln!(out, "alias {name} = {cmd}", name = a.name, cmd = a.command,).unwrap();
            } else {
                // nushell alias can include args
                writeln!(
                    out,
                    "alias {name} = {cmd} {args}",
                    name = a.name,
                    cmd = a.command,
                    args = a.args.join(" "),
                )
                .unwrap();
            }
        }
        writeln!(out).unwrap();
    }

    // Script wrappers (.ps1 via pwsh)
    if !defs.script.is_empty() {
        writeln!(out, "# --- Script wrappers ---").unwrap();
        for s in &defs.script {
            let segments = s
                .path
                .replace('\\', "/")
                .split('/')
                .map(|seg| format!("\"{seg}\""))
                .collect::<Vec<_>>()
                .join(" ");
            writeln!(
                out,
                "def {name} [...args: string] {{ pwsh -File ([\"{dotfiles}\" {segments}] | path join) ...$args }}",
                name = s.name,
                segments = segments,
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // Launchers (Windows — nushell `start` opens URIs and exes)
    let win_launchers: Vec<_> = defs
        .launcher
        .iter()
        .filter(|l| l.platform.as_ref() != Some(&Platform::Macos) && l.nushell)
        .collect();
    if !win_launchers.is_empty() {
        writeln!(out, "# --- Launchers ---").unwrap();
        for l in &win_launchers {
            match l.launcher_type {
                LauncherType::Uri => {
                    writeln!(
                        out,
                        "def {name} [] {{ start {uri} }}",
                        name = l.name,
                        uri = l.uri.as_ref().unwrap(),
                    )
                    .unwrap();
                }
                LauncherType::Exe => {
                    let raw_path = l.path.as_ref().unwrap();
                    let path_expr = if raw_path.contains("{PROGRAM_FILES}") {
                        let rest = raw_path
                            .replace("{PROGRAM_FILES}\\", "")
                            .replace("{PROGRAM_FILES}", "");
                        let segments = rest
                            .split('\\')
                            .filter(|s| !s.is_empty())
                            .map(|s| format!("\"{s}\""))
                            .collect::<Vec<_>>()
                            .join(" ");
                        format!("([$env.ProgramFiles {segments}] | path join)")
                    } else if raw_path.contains('\\') {
                        // nushell の "" 内では \ がエスケープ扱いになるため
                        // path join でセグメント結合する
                        let segments = raw_path
                            .split('\\')
                            .map(|s| format!("\"{s}\""))
                            .collect::<Vec<_>>()
                            .join(" ");
                        format!("([{segments}] | path join)")
                    } else {
                        // Bare executable name (no path separators) — cannot use
                        // `start` which expects a file/URI. Use `^` to invoke via PATH.
                        raw_path.to_string()
                    };
                    let is_bare = !raw_path.contains('\\') && !raw_path.contains("{PROGRAM_FILES}");
                    if l.args.is_empty() {
                        if is_bare {
                            writeln!(
                                out,
                                "def {name} [] {{ ^{path} }}",
                                name = l.name,
                                path = path_expr,
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                out,
                                "def {name} [] {{ start {path} }}",
                                name = l.name,
                                path = path_expr,
                            )
                            .unwrap();
                        }
                    } else {
                        let args_str = l
                            .args
                            .iter()
                            .map(|a| {
                                let escaped = a.replace('"', r#"\""#);
                                format!("\"{escaped}\"")
                            })
                            .collect::<Vec<_>>()
                            .join(" ");
                        writeln!(
                            out,
                            "def {name} [] {{ ^{path} {args} }}",
                            name = l.name,
                            path = path_expr,
                            args = args_str,
                        )
                        .unwrap();
                    }
                }
                LauncherType::StartApp => {
                    // start_app is PowerShell-specific, skip for nushell
                }
            }
        }
        writeln!(out).unwrap();
    }

    // Complex commands (dotcli subcommands)
    let cmds: Vec<_> = defs.command.iter().filter(|c| c.enabled).collect();
    if !cmds.is_empty() {
        writeln!(out, "# --- Commands (via dotcli) ---").unwrap();
        for c in &cmds {
            if c.modifies_shell {
                writeln!(
                    out,
                    "def --env {name} [...args: string] {{ dotcli {sub} ...$args | _dotcli_apply }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "def {name} [...args: string] {{ dotcli {sub} ...$args }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            }
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::generate;
    use crate::definitions::{Definitions, Platform};
    use crate::generate::powershell;
    use std::path::Path;
    use std::process::Command;

    fn dotfiles_path() -> &'static Path {
        Path::new("C:/Main/dotfiles")
    }

    fn nu_available() -> bool {
        Command::new("nu")
            .arg("--version")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
    }

    #[test]
    fn nushell_covers_definitions_present_in_powershell() {
        let defs = Definitions::load();
        let ps = powershell::generate(&defs, dotfiles_path());
        let nu = generate(&defs, dotfiles_path());

        for a in &defs.alias {
            let marker = format!("function {} {{", a.name);
            assert!(
                ps.contains(&marker),
                "alias {} expected in PowerShell output",
                a.name
            );
            let marker = format!("alias {} =", a.name);
            assert!(
                nu.contains(&marker),
                "alias {} missing from nushell output",
                a.name
            );
        }

        for s in &defs.script {
            let marker = format!("function {} {{", s.name);
            assert!(
                ps.contains(&marker),
                "script {} expected in PowerShell output",
                s.name
            );
            let marker = format!("def {} [", s.name);
            assert!(
                nu.contains(&marker),
                "script {} missing from nushell output",
                s.name
            );
        }

        for l in &defs.launcher {
            if l.platform.as_ref() == Some(&Platform::Macos) {
                continue;
            }
            let ps_marker = format!("function {} {{", l.name);
            assert!(
                ps.contains(&ps_marker),
                "launcher {} expected in PowerShell output",
                l.name
            );
            let nu_marker = format!("def {} [", l.name);
            if l.nushell {
                assert!(
                    nu.contains(&nu_marker),
                    "launcher {} missing from nushell output",
                    l.name
                );
            } else {
                assert!(
                    !nu.contains(&nu_marker),
                    "launcher {} should be excluded from nushell output",
                    l.name
                );
            }
        }

        for c in &defs.command {
            if !c.enabled {
                let marker = format!("function {} {{", c.name);
                assert!(
                    !ps.contains(&marker),
                    "disabled command {} must not appear in PowerShell output",
                    c.name
                );
                assert!(
                    !nu.contains(&format!("def {} [", c.name))
                        && !nu.contains(&format!("def --env {} [", c.name)),
                    "disabled command {} must not appear in nushell output",
                    c.name
                );
                continue;
            }
            let marker = format!("function {} {{", c.name);
            assert!(
                ps.contains(&marker),
                "command {} expected in PowerShell output",
                c.name
            );
            let marker = if c.modifies_shell {
                format!("def --env {} [", c.name)
            } else {
                format!("def {} [", c.name)
            };
            assert!(
                nu.contains(&marker),
                "command {} missing from nushell output",
                c.name
            );
        }
    }

    #[test]
    fn nushell_generated_passes_ide_check() {
        if !nu_available() {
            return;
        }
        let defs = Definitions::load();
        let nu_src = generate(&defs, dotfiles_path());
        let path = std::env::temp_dir().join(format!(
            "dotcli-ide-check-{}.nu",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::write(&path, &nu_src).unwrap();
        let status = Command::new("nu")
            .args(["--ide-check", "0", path.to_str().unwrap()])
            .status()
            .expect("failed to spawn nu");
        let _ = std::fs::remove_file(&path);
        assert!(
            status.success(),
            "nu --ide-check failed with status {:?}",
            status.code()
        );
    }
}

const APPLY_HELPER: &str = r#"def --env _dotcli_apply [] {
    let action = ($in | from json)
    if ($action | get -o unset_env | is-not-empty) {
        for k in $action.unset_env { hide-env -i $k }
    }
    if ($action | get -o set_env | is-not-empty) {
        load-env $action.set_env
    }
    if ($action | get -o cd | is-not-empty) { cd $action.cd }
    if ($action | get -o messages | is-not-empty) {
        $action.messages | each { |m|
            let color = match $m.level { "warn" => "yellow", "error" => "red", _ => "green" }
            print $"(ansi $color)($m.text)(ansi reset)"
        } | ignore
    }
    if ($action | get -o exec | is-not-empty) {
        ^($action.exec.program) ...($action.exec.args)
    }
}
"#;
