use crate::definitions::{Definitions, LauncherType, Platform};
use std::fmt::Write;
use std::path::Path;

pub fn generate(defs: &Definitions, dotfiles_dir: &Path) -> String {
    let mut out = String::new();
    let dotfiles = dotfiles_dir.to_string_lossy().replace('\\', "/");

    writeln!(out, "# Auto-generated by dotcli — DO NOT EDIT").unwrap();
    writeln!(out).unwrap();

    // _dotcli_apply helper
    writeln!(out, "{}", APPLY_HELPER).unwrap();

    // Aliases
    if !defs.alias.is_empty() {
        writeln!(out, "# --- Aliases ---").unwrap();
        for a in &defs.alias {
            if a.args.is_empty() {
                writeln!(out, "alias {name} = {cmd}", name = a.name, cmd = a.command,).unwrap();
            } else {
                // nushell alias can include args
                writeln!(
                    out,
                    "alias {name} = {cmd} {args}",
                    name = a.name,
                    cmd = a.command,
                    args = a.args.join(" "),
                )
                .unwrap();
            }
        }
        writeln!(out).unwrap();
    }

    // Script wrappers (.ps1 via pwsh)
    if !defs.script.is_empty() {
        writeln!(out, "# --- Script wrappers ---").unwrap();
        for s in &defs.script {
            let segments = s
                .path
                .replace('\\', "/")
                .split('/')
                .map(|seg| format!("\"{seg}\""))
                .collect::<Vec<_>>()
                .join(" ");
            writeln!(
                out,
                "def {name} [...args: string] {{ pwsh -File ([\"{dotfiles}\" {segments}] | path join) ...$args }}",
                name = s.name,
                segments = segments,
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // Launchers (Windows — nushell `start` opens URIs and exes)
    let win_launchers: Vec<_> = defs
        .launcher
        .iter()
        .filter(|l| l.platform.as_ref() != Some(&Platform::Macos))
        .collect();
    if !win_launchers.is_empty() {
        writeln!(out, "# --- Launchers ---").unwrap();
        for l in &win_launchers {
            match l.launcher_type {
                LauncherType::Uri => {
                    writeln!(
                        out,
                        "def {name} [] {{ start {uri} }}",
                        name = l.name,
                        uri = l.uri.as_ref().unwrap(),
                    )
                    .unwrap();
                }
                LauncherType::Exe => {
                    let raw_path = l.path.as_ref().unwrap();
                    let path_expr = if raw_path.contains("{PROGRAM_FILES}") {
                        let rest = raw_path
                            .replace("{PROGRAM_FILES}\\", "")
                            .replace("{PROGRAM_FILES}", "");
                        let segments = rest
                            .split('\\')
                            .filter(|s| !s.is_empty())
                            .map(|s| format!("\"{s}\""))
                            .collect::<Vec<_>>()
                            .join(" ");
                        format!("([$env.ProgramFiles {segments}] | path join)")
                    } else if raw_path.contains('\\') {
                        // nushell の "" 内では \ がエスケープ扱いになるため
                        // path join でセグメント結合する
                        let segments = raw_path
                            .split('\\')
                            .map(|s| format!("\"{s}\""))
                            .collect::<Vec<_>>()
                            .join(" ");
                        format!("([{segments}] | path join)")
                    } else {
                        // Bare executable name (no path separators) — cannot use
                        // `start` which expects a file/URI. Use `^` to invoke via PATH.
                        raw_path.to_string()
                    };
                    let is_bare = !raw_path.contains('\\')
                        && !raw_path.contains("{PROGRAM_FILES}");
                    if l.args.is_empty() {
                        if is_bare {
                            writeln!(
                                out,
                                "def {name} [] {{ ^{path} }}",
                                name = l.name,
                                path = path_expr,
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                out,
                                "def {name} [] {{ start {path} }}",
                                name = l.name,
                                path = path_expr,
                            )
                            .unwrap();
                        }
                    } else {
                        let args_str = l.args.iter().map(|a| {
                            let escaped = a.replace('"', r#"\""#);
                            format!("\"{escaped}\"")
                        }).collect::<Vec<_>>().join(" ");
                        writeln!(
                            out,
                            "def {name} [] {{ ^{path} {args} }}",
                            name = l.name,
                            path = path_expr,
                            args = args_str,
                        )
                        .unwrap();
                    }
                }
                LauncherType::StartApp => {
                    // start_app is PowerShell-specific, skip for nushell
                }
            }
        }
        writeln!(out).unwrap();
    }

    // Complex commands (dotcli subcommands)
    let cmds: Vec<_> = defs.command.iter().filter(|c| c.enabled).collect();
    if !cmds.is_empty() {
        writeln!(out, "# --- Commands (via dotcli) ---").unwrap();
        for c in &cmds {
            if c.modifies_shell {
                writeln!(
                    out,
                    "def {name} [...args: string] {{ dotcli {sub} ...$args | _dotcli_apply }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "def {name} [...args: string] {{ dotcli {sub} ...$args }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            }
        }
    }

    out
}

const APPLY_HELPER: &str = r#"def _dotcli_apply [] {
    let action = ($in | from json)
    if ($action | get -o set_env | is-not-empty) {
        $action.set_env | transpose k v | each { |r| load-env {($r.k): $r.v} } | ignore
    }
    if ($action | get -o unset_env | is-not-empty) {
        $action.unset_env | each { |k| hide-env $k } | ignore
    }
    if ($action | get -o cd | is-not-empty) { cd $action.cd }
    if ($action | get -o messages | is-not-empty) {
        $action.messages | each { |m| print $m.text } | ignore
    }
    if ($action | get -o exec | is-not-empty) {
        ^($action.exec.program) ...($action.exec.args)
    }
}
"#;
