use crate::definitions::{Definitions, LauncherType, Platform};
use std::fmt::Write;
use std::path::Path;

pub fn generate(defs: &Definitions, dotfiles_dir: &Path) -> String {
    let mut out = String::new();
    let dotfiles = dotfiles_dir.display();

    writeln!(out, "# Auto-generated by dotcli — DO NOT EDIT").unwrap();
    writeln!(out).unwrap();

    // _dotcli_apply helper
    writeln!(out, "{}", APPLY_HELPER).unwrap();

    // Aliases
    if !defs.alias.is_empty() {
        writeln!(out, "# --- Aliases ---").unwrap();
        for a in &defs.alias {
            let args_str = if a.args.is_empty() {
                String::new()
            } else {
                format!(" {}", a.args.join(" "))
            };
            writeln!(
                out,
                "function {name} {{ {cmd}{args} @args }}",
                name = a.name,
                cmd = a.command,
                args = args_str,
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // Script wrappers
    if !defs.script.is_empty() {
        writeln!(out, "# --- Script wrappers ---").unwrap();
        for s in &defs.script {
            writeln!(
                out,
                "function {name} {{ & \"{dotfiles}\\{path}\" @args }}",
                name = s.name,
                path = s.path.replace('/', "\\"),
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    // Launchers (Windows only for now)
    let win_launchers: Vec<_> = defs
        .launcher
        .iter()
        .filter(|l| l.platform.as_ref() != Some(&Platform::Macos))
        .collect();
    if !win_launchers.is_empty() {
        writeln!(out, "# --- Launchers ---").unwrap();
        for l in &win_launchers {
            match l.launcher_type {
                LauncherType::Uri => {
                    writeln!(
                        out,
                        "function {name} {{ explorer {uri} }}",
                        name = l.name,
                        uri = l.uri.as_ref().unwrap(),
                    )
                    .unwrap();
                }
                LauncherType::StartApp => {
                    writeln!(
                        out,
                        "function {name} {{ Start-App \"{app}\" }}",
                        name = l.name,
                        app = l.app_name.as_ref().unwrap(),
                    )
                    .unwrap();
                }
                LauncherType::Exe => {
                    let path = l
                        .path
                        .as_ref()
                        .unwrap()
                        .replace("{PROGRAM_FILES}", "$env:ProgramFiles");
                    if l.args.is_empty() {
                        writeln!(out, "function {name} {{ start \"{path}\" }}", name = l.name,)
                            .unwrap();
                    } else {
                        let args_str = l
                            .args
                            .iter()
                            .map(|a| format!("'{a}'"))
                            .collect::<Vec<_>>()
                            .join(",");
                        writeln!(
                            out,
                            "function {name} {{ start \"{path}\" -Arg {args} }}",
                            name = l.name,
                            args = args_str,
                        )
                        .unwrap();
                    }
                }
            }
        }
        writeln!(out).unwrap();
    }

    // Complex commands (dotcli subcommands)
    let cmds: Vec<_> = defs.command.iter().filter(|c| c.enabled).collect();
    if !cmds.is_empty() {
        writeln!(out, "# --- Commands (via dotcli) ---").unwrap();
        for c in &cmds {
            if c.modifies_shell {
                writeln!(
                    out,
                    "function {name} {{ dotcli {sub} @args | _dotcli_apply }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "function {name} {{ dotcli {sub} @args }}",
                    name = c.name,
                    sub = c.subcommand,
                )
                .unwrap();
            }
        }
    }

    out
}

const APPLY_HELPER: &str = r#"function _dotcli_apply {
    param([Parameter(ValueFromPipeline)][string]$Json)
    $a = $Json | ConvertFrom-Json
    if ($a.set_env) {
        $a.set_env.PSObject.Properties | % { Set-Item "env:$($_.Name)" $_.Value }
    }
    if ($a.unset_env) {
        $a.unset_env | % { Remove-Item "env:$_" -ea 0 }
    }
    if ($a.cd) { Set-Location $a.cd }
    if ($a.messages) {
        $a.messages | % {
            $c = switch ($_.level) { 'warn' { 'Yellow' } 'error' { 'Red' } default { 'Green' } }
            wh $_.text -ForegroundColor $c
        }
    }
    if ($a.exec) { & $a.exec.program @($a.exec.args) }
}
"#;
