# Auto-generated by dotcli — DO NOT EDIT

_dotcli_apply() {
    local json
    json=$(cat)
    [ -z "$json" ] && return 0
    if ! command -v jq >/dev/null 2>&1; then
        printf 'dotcli: jq is required for shell-modifying commands\n' >&2
        return 1
    fi
    local key val cd_path lvl txt prog
    while IFS= read -r key; do [ -n "$key" ] && unset "$key"; done < <(printf '%s' "$json" | jq -r '.unset_env[]? // empty')
    while IFS=$'\t' read -r key val; do [ -n "$key" ] && export "$key=$val"; done < <(printf '%s' "$json" | jq -r '.set_env // {} | to_entries[] | "\(.key)\t\(.value)"')
    cd_path=$(printf '%s' "$json" | jq -r '.cd // empty')
    [ -n "$cd_path" ] && cd "$cd_path"
    while IFS=$'\t' read -r lvl txt; do
        case "$lvl" in
            warn) printf '\033[33m%s\033[0m\n' "$txt" ;;
            error) printf '\033[31m%s\033[0m\n' "$txt" ;;
            *) printf '\033[32m%s\033[0m\n' "$txt" ;;
        esac
    done < <(printf '%s' "$json" | jq -r '.messages[]? | "\(.level)\t\(.text)"')
    prog=$(printf '%s' "$json" | jq -r '.exec.program // empty')
    if [ -n "$prog" ]; then
        if [ "$prog" = "claude" ]; then
            printf '\033]1337;SetUserVar=app=Y2xhdWRl\007'
        fi
        local exec_args=()
        local arg
        while IFS= read -r arg; do exec_args+=("$arg"); done < <(printf '%s' "$json" | jq -r '.exec.args[]? // empty')
        exec "$prog" "${exec_args[@]}"
    fi
}

# --- Aliases ---
lg() { lazygit "$@"; }
v() { nvim "$@"; }
f() { fzf "$@"; }
fm() { fzf '-m' "$@"; }
agy() { antigravity '.' "$@"; }
zp() { zoxide 'query' '-i' "$@"; }
z-() { z '-' "$@"; }

# --- Script wrappers ---
gnew() { pwsh -NoProfile -File 'C:/Main/Project/dotfiles/bin/git-new.ps1' "$@"; }
toggle-theme() { pwsh -NoProfile -File 'C:/Main/Project/dotfiles/bin/toggle-theme.ps1' "$@"; }
audio() { pwsh -NoProfile -File 'C:/Main/Project/dotfiles/bin/switch-audio.ps1' "$@"; }
ycusage() { pwsh -NoProfile -File 'C:/Main/Project/dotfiles/bin/ycusage.ps1' "$@"; }
claude-reauth() { pwsh -NoProfile -File 'C:/Main/Project/dotfiles/bin/claude-reauth.ps1' "$@"; }

# --- Launchers ---
kindle() { explorer.exe 'kindle:'; }
dis() { explorer.exe 'discord:'; }
slk() { explorer.exe 'slack:'; }
obsd() { explorer.exe 'obsidian:'; }
viv() { pwsh -NoProfile -Command 'Start-Process -FilePath '\''vivaldi'\'''; }
rmt() { explorer.exe 'parsec:'; }
spotify() { explorer.exe 'spotify:'; }
ncal() { pwsh -NoProfile -Command 'explorer "shell:AppsFolder\$((Get-StartApps '\''Notion Calendar'\'' | Select-Object -First 1).AppID)"'; }
htb() { pwsh -NoProfile -Command 'Start-Process -FilePath '\''C:\Main\Project\HideTaskBar-temp\src\HideTaskBar\bin\Debug\net8.0-windows\HideTaskBar.exe'\'''; }
lghub() { pwsh -NoProfile -Command 'Start-Process -FilePath "$env:ProgramFiles\LGHUB\system_tray\lghub_system_tray.exe" -ArgumentList '\''--minimized'\'''; }
nvbc() { pwsh -NoProfile -Command 'Start-Process -FilePath "$env:ProgramFiles\NVIDIA Corporation\NVIDIA Broadcast\NVIDIA Broadcast.exe" -ArgumentList '\''--process-start-args "--launch-hidden"'\'''; }

# --- Commands (via dotcli) ---
proxy() { local _o; _o=$(dotcli proxy "$@"); _dotcli_apply <<<"$_o"; }
c() { local _o; _o=$(dotcli claude-switch "$@"); _dotcli_apply <<<"$_o"; }
a() { local _o; _o=$(dotcli cursor-agent "$@"); _dotcli_apply <<<"$_o"; }
cb() { local _o; _o=$(dotcli claude-bedrock "$@"); _dotcli_apply <<<"$_o"; }
cg() { local _o; _o=$(dotcli claude-glm "$@"); _dotcli_apply <<<"$_o"; }
grf() { dotcli grf "$@"; }
grfo() { dotcli grfo "$@"; }
grfc() { dotcli grfc "$@"; }
frun() { dotcli frun "$@"; }
locked() { dotcli locked "$@"; }
dotb() { dotcli build "$@"; }
